// Generated by IcedCoffeeScript 1.6.3-f
(function() {
  var Claps, Jaws, Main, main,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };



  Jaws = (function() {
    Jaws.prototype.STATES = {
      HIDING: 1,
      HIDDEN: 2,
      PEEKING: 3,
      CHOMPING: 4
    };

    Jaws.prototype.HEIGHT = 100;

    Jaws.prototype.PEEK_TIME = 1000;

    Jaws.prototype.TRANSITION_TIME = 500;

    Jaws.prototype.CHOMP_COOLDOWN = 1000;

    Jaws.prototype.DONE_COOLDOWN = 2500;

    Jaws.prototype.TEETH_PERCENT = .3;

    Jaws.prototype.closed = false;

    Jaws.prototype.couldChomp = false;

    Jaws.prototype.doneTimer = null;

    function Jaws() {
      this.state = this.STATES.HIDDEN;
      $('body').prepend("<div id=\"monster-t\">\n    <div class=\"monster-l\"></div>\n    <div class=\"monster-m\"></div>\n    <div class=\"monster-r\"></div>\n</div>\n<div id=\"monster-b\">\n    <div class=\"monster-l\"></div>\n    <div class=\"monster-m\"></div>\n    <div class=\"monster-r\"></div>\n</div>");
    }

    Jaws.prototype.tween = function(percentClosed) {
      if (this.state === this.STATES.CHOMPING) {
        this.chompTween(percentClosed);
      } else if (this.state !== this.STATES.HIDING) {
        this.peek(percentClosed);
      }
    };

    Jaws.prototype.peek = function(percentClosed) {
      var pixelOffset;
      pixelOffset = percentClosed * this.HEIGHT - this.HEIGHT;
      this.state = this.STATES.PEEKING;
      $('#monster-t').css('top', pixelOffset);
      $('#monster-b').css('bottom', pixelOffset);
      if (percentClosed === 1) {
        this.closed = true;
        if (this.couldChomp) {
          this.chomp();
          this.couldChomp = false;
        }
      } else if (this.closed) {
        this.closed = false;
        this.couldChomp = true;
        this.startChompTimer();
      }
    };

    Jaws.prototype.chompTween = function(percentClosed) {
      var adjustedHeight, pixelOffset;
      adjustedHeight = this.HEIGHT * (1 - this.TEETH_PERCENT);
      pixelOffset = percentClosed * adjustedHeight - adjustedHeight;
      pixelOffset = pixelOffset > 0 ? 0 : pixelOffset;
      $('#monster-t').css('top', pixelOffset);
      $('#monster-b').css('bottom', pixelOffset);
      if (percentClosed === 1) {
        this.closed = true;
        if (this.couldChomp) {
          this.chomp();
          this.couldChomp = false;
          this.startDoneTimer();
        }
      } else if (this.closed) {
        this.closed = false;
        this.couldChomp = true;
      }
    };

    Jaws.prototype.chomp = function() {
      this.state = this.STATES.CHOMPING;
      this.resetDoneTimer();
      console.log("CHOMP");
    };

    Jaws.prototype.hide = function() {
      var _this = this;
      this.state = this.STATES.HIDING;
      this.couldChomp = false;
      this.closed = false;
      this.hideHalf('#monster-t', 'top');
      this.hideHalf('#monster-b', 'bottom');
      setTimeout(function() {
        _this.state = _this.STATES.HIDDEN;
        _this.submitWreckage();
      }, this.TRANSITION_TIME);
    };

    Jaws.prototype.hideHalf = function(selector, property) {
      var props;
      props = {};
      props[property] = -this.HEIGHT;
      $(selector).animate(props, this.TRANSITION_TIME);
    };

    Jaws.prototype.reset = function() {
      if (this.state !== this.STATES.CHOMPING) {
        this.state = this.STATES.HIDDEN;
        $('#monster-t').css('top', -this.HEIGHT);
        $('#monster-b').css('bottom', -this.HEIGHT);
      }
    };

    Jaws.prototype.startChompTimer = function() {
      var _this = this;
      setTimeout(function() {
        _this.couldChomp = false;
      }, this.CHOMP_COOLDOWN);
    };

    Jaws.prototype.startDoneTimer = function() {
      var _this = this;
      if (this.doneTimer != null) {
        return;
      }
      this.doneTimer = setTimeout(function() {
        _this.hide();
      }, this.DONE_COOLDOWN);
    };

    Jaws.prototype.resetDoneTimer = function() {
      if (this.doneTimer != null) {
        clearTimeout(this.doneTimer);
        this.doneTimer = null;
        return this.startDoneTimer();
      }
    };

    Jaws.prototype.submitWreckage = function() {
      console.log("THIS SITE GOT WRECKED");
    };

    return Jaws;

  })();

  Claps = (function() {
    Claps.prototype.STATES = {
      HIDDEN: 0,
      HIDING: 1,
      CLAPPING: 2
    };

    Claps.prototype.number_of_claps = 0;

    function Claps() {
      this.state = this.STATES.HIDDEN;
      $('body').prepend("<div class='left-hand'>\n	<h1> A BIG LEFT HAND </h1>\n</div>\n<div class='right-hand'>\n	<h1> A BIG RIGHT HAND </h1>\n</div>");
      console.log("In the constructor");
      return;
    }

    Claps.prototype.clapping = function() {
      this.state = this.STATES.CLAPPING;
      console.log("A clap!");
    };

    Claps.prototype.submitRespect = function() {
      console.log("GIVE THIS SITE SOME RESPECT");
    };

    return Claps;

  })();

  Main = (function() {
    Main.MIN_WIDTH = 400;

    Main.MIN_HEIGHT = 200;

    Main.PEEK_THRESHOLD = 300;

    function Main() {
      this.onResize = __bind(this.onResize, this);
      this.jaws = new Jaws;
      this.claps = new Claps;
      $(window).resize(this.onResize);
    }

    Main.prototype.onResize = function() {
      this.resizeHeight($(window).height());
      this.resizeWidth($(window).width());
    };

    Main.prototype.resizeHeight = function(height) {
      var percentClosed, pixelsToClose;
      if (height < Main.PEEK_THRESHOLD) {
        pixelsToClose = height - Main.MIN_HEIGHT;
        percentClosed = 1 - (pixelsToClose / (Main.PEEK_THRESHOLD - Main.MIN_HEIGHT));
        this.jaws.tween(percentClosed);
      } else {
        this.jaws.reset();
      }
    };

    Main.prototype.resizeWidth = function(width) {};

    return Main;

  })();

  main = new Main;

}).call(this);
